language: node_js
node_js:
  - 14
branches:
  only:
    - prod
    - dev
cache: yarn
script:
  - yarn
notifications:
  slack:
    secure: MVjOZrNZDllrTBBZKybLd2s/kls2XqNpmL8v3nluFJf/PyHqk2tIDRr+CK4TUc1cZqt7x+eC4RIUnOSvdHq68r3WcDvTTsPxNvi1mZ38GztzqMZV7XAlMzXJjD7LmHk7kWVBZc5hLbRvh2M/jul8gZmMwSGwJ3yq3lhec+1y2Rvko/no532RKITNX0t7ZPVUl6U2Et+8XKfQqxG66GwCfaMrQJ8042nDobdPJyL3QOitfWjaZfvYVlbQAZZiIeGqQBOzPSuHid6ksSV8T8oTGr+eRK7zwX45l9oUxrblelow4JdE/QeLhmpODTnJJeASUzXuFKMS7pcr7X+rgVBAQRCRQHFlR8ra7QfYTYeiD/u9tnuczlvM1ZZ4iC78jy9x9LueQam5fnbOGRxkYz1XzQah1Ceh/Zl9N1TcylkVdTgWfhUa3KyvAQzX5ugUTAGuJQOICWdMkL6lRiL4qbaLubtsaXG7QcIJrDjPjo+FFSafYtqODRLws/AZF/svvHEulEY7j/6MGEGf56/2dvT17oDBn8+uerUMxVqeil+Huquu7n3z03CM7M7J+lqgC64HJ0lr82gvpg1tbEjXM0nAuyYMrNBFPQJPUHgkB0rVJ0L2BjAkdG4liQPRziTnhVUFnO+YuagkJdPZPQ/M/DVwW8ebx9JwXzHXYywUaZLF9mQ=
deploy:
  - provider: openshift
    server: '$OPENSHIFT_SERVER'
    project: gala
    app:
      prod: gala-website-front-prod
      dev: gala-website-front-dev
    token: '$OPENSHIFT_TOKEN'
    edge: true
