language: node_js
node_js:
  - 14
branches:
  only:
    - prod
    - dev
cache: yarn
script:
  - yarn
notifications:
  slack:
    secure: I1oIWbn28540d7rA7G/s8YpFNiFmiXH0Vpsfi1Dcn1kYM73RLVQIPyUW3FK+CLEeTUtq9FWuwz6i18hLHrxNyGKXNzvazFpktxQOMjUx/pXAQiKDSSnxTs0i73CwSd+XgT+Db/sogzqzBpGvsRuDV3Q88fcu9Y//5WtsjNzOK0EEvtsvV7ypxFZi/vhagoqMaDI/0w7Xdwliwsc4pPhbfZAN7utJbvjNI1/hq3+z/+oB6kKBNLAP6PnDNAwGARhEV2DSHnX/6sVSjLPoE2D4M1fMDCBCEzuR1r+Pb0bkaBHPL3nKyxkc2cywLBzTrf4v5rhOxcUapZ6OCpHzI7VKodpttm/hDgxK/wQ/GAeI9DIEodiy21l+Ij9exq5psEupkaruw0Z5S7a6bIaln/gBPQmHJ11kyKrnWV61/THGN8WX7dCVM4uVTXP5freejd3gb8AiKTnxXrl1HvsXUo+TSb5WRTOkvkrmgpDfbYndTiEp/Nxc1RTsCbmCh6K6G2J+iRk13wADtQFOediEyEHpc+jXMSAAXQKkJKerDDVDheFlkzb5ZVS7lQTRrAtheR9973jWIIEoopYFaEb2DPnuAZvOnoK2Khk/eRGVoRWr3xxlIalhYasgrt9LAlV26hjZw512gKlj5ALWybud/Cy9oRP7MbjID/Dsa2opMe+GMAg=
deploy:
  - provider: openshift
    server: '$OPENSHIFT_SERVER'
    project: gala
    app:
      prod: gala-website-front-prod
      dev: gala-website-front-dev
    token: '$OPENSHIFT_TOKEN'
    edge: true
