language: node_js
node_js:
  - 14
branches:
  only:
    - prod
    - dev
cache: yarn
script:
  - yarn
notifications:
  slack:
    secure: ryKeX1WPloQwKJV+PCj31auCLgj6pGQQ6XOm2i8luN9qHRH72KxdACgHhEdEyM8hlzhh0BfI/nwrgPeVD1xpIF6MWPXNtw4pJeirvBVu9ms13Bzep987Qe0fK/AMdDfo0mqC+2TwLj1RVJqAMx1AGXJGjGJIT3vcCnpXbgdgtUBG1dCtgxo1CTrz7JrikanRxMeKJLrC1X/yp0bA8Ec51Yf5jRJgSNU7t4E8Bco3lK+Kw1Egyju8/SDCbUiVPi5LIj5hEcswTr8HUZavu+iMbf0Qcb35Aty8X7MFCl00L/l81YbWz9j1NNVqk1ar2WmXcbJPzUTYwrtLtSJwdOYvR8sSFiICLJaXplivRd6Lkp2OHQbTGMuqM1ACzaK3Do34IdM0E09M/mugFV5pOxSqELd7KpVVYffT2LNTx4X1xukwKfK3O2jtsNt2ggd3M3UZz8zW3aqsOjytL4DZ9ddts4qwus4nFjGpxcWEN0ToysYPGXVU3wA/J/XKVWoD0j0i0Rmn0z6X50BOX5ZwaJAZ8TMqkctEu0YMDiGx/E32uKbgEFXiuhHDH8Y0FLC+UpqRAfIeqPcXIp1LlQQVvQk2x0t9Q0ddLoyqkmpVlxC6KpXQvtSsitGPMf3wJbz0U0boq6rsa/IcukAVtrwFDP47c9ReFI/obuqSyJjEQzZ/nUo=
deploy:
  - provider: openshift
    server: '$OPENSHIFT_SERVER'
    project: gala
    app:
      prod: gala-website-front-prod
      dev: gala-website-front-dev
    token: '$OPENSHIFT_TOKEN'
    edge: true
