language: node_js
node_js:
- 13
branches:
  only:
  - master
  - dev
cache: yarn
script:
- yarn
notifications:
  slack:
    secure: UpjpGwr8ssAI8ZDdpo0YK4B02d9pXpR01bDg1osOpyu7tf6H0fI+yr6Y3sPpRkhaA1AtaCbL/Kl0tUtneMtaVqhvbPkmKIVpkEU/nwOp+ZUUbsMgKdlKhrX0R+9sOek9GoNoumx6eNVIqQEdYfg7YEkpZXaH5/MJYTrJ8q98NiwMfLnqJ0ZsJYTUTTyQ06YkPaJunxTxe3tXfISj2O9u2WxOYSchpllU1s/PQy4A8y6eDKCNcZ0M9L7KCbkYuxw0hLWXJu59FyUAWHUl8VW32+fkEUUixW5L69vHJKlHrSnzBsIxRKAYMK88wEPA2cOQBt8Q6YXvUQrdB4Vw4RjZcWg5QxE2oxZqDp65SBz6dRAsky8QtCt9HaTHbwJ6UuxH9NXLL+7Ay7NUsfcM+cBs/xXCQ9FZsgDC4hrRohCNZH+jiL657J8ahjBb1AxvxeFBbBAYSYNSwhQWPAgXqAaJHSDcGpek1UMqaLefn7q4xg+UD6QH+mDpJJ+L45Nr8WRv/W+pt/wUCmNsdg/Oi32PRV+nyxW8IN5hn+KnB0ypwiniKQmuiwXh1Id6g/NZ2w9AKYkI4AwpXAvnDz8L75At6zXflleyVQG6ztjV6+K4EP6PH7wqmOV6ymlxlTueqRDwWi+zcZKg/FizvXcBkpn4k02xNBB56Q8WIxO2BgSIUag=
deploy:
- provider: openshift
  server: "$OPENSHIFT_SERVER"
  project: gala
  app:
    master: gala-website-front-prod
    dev: gala-website-front-dev
  token: "$OPENSHIFT_TOKEN"
  edge: true
