language: node_js
node_js:
  - 14
branches:
  only:
    - prod
    - dev
cache: yarn
script:
  - yarn
notifications:
  slack:
    secure: nw05uowqXTDTwcKofxfWKky5VrbEJ6fOK5zeox8l5hJkL4Xby6QCWAueoAWLo1xqchV4xLJb4GEGzejUeXKA1XX0KhHQzehYJYJSrpLmy3uVWb9WOe382+uPEFLX/jibeOKX18iFCRcBrC7myKigdAIfkBu7NuNoc7dC+Ep4ii1rGL2pj1XD7NTVGIqjEcXILlxdRhGU14+UtcqqinNtHDyGwF3htt/PZhZ5lQ6Xetzzy/vTXMQ/EuItvaXPGj+HSjN45HoJxCvG4a7D53/gQvOENI8F9j8KUKqoxP2x0higTSVF+f/0viWwOzE+fHnmKZ4LXP9WzGn934IVzmfhP48dmoL+rJ8WZXH9DQL6jpGnAviLpwquQWJ4c3nZJQunnTNM7fbYaLgwUq9qFe79HfGPcP8Xr/thw3HWkmb4NWp+eym/ZA5+OlTsglL0+2S/Qv9zPup7ik8Ne7VXpJ52b96Ql9XQzqn1E4tslZIfrB/6mmqTMYoJx4BVntUjD+YxiRjALsIAre2M4hcmwW01gRqRAW2kjpOY3lbvgWJl2Sgbe8SMyjsyM1iCGqdIVPJMAA6xyOJMgtfyCYu0m2cWArn46PzyU57bsgkRe+nf6C4tKg520JfcB3xe2MGbXjJUq/JfmIzvAzI5jdSIzfAjh7lAWVCP76WxNNW/pcm62fc=
deploy:
  - provider: openshift
    server: '$OPENSHIFT_SERVER'
    project: gala
    app:
      prod: gala-website-front-prod
      dev: gala-website-front-dev
    token: '$OPENSHIFT_TOKEN'
    edge: true
