language: node_js

node_js:
  - 13

branches:
  only:
    - master
    - dev

cache: yarn

script:
  - yarn

notifications:
  slack: gala-utt:vVVBOZLgv9F8lMpJz67eYCym

deploy:
  - provider: openshift
    server: $OPENSHIFT_SERVER
    project: gala
    app:
      master: gala-website-front-prod
      dev: gala-website-front-dev
    token: $OPENSHIFT_TOKEN
    edge: true
